name: Tests

on:
  pull_request:
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm test

  ubuntu-action-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          name: "unbuntu unit tests"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report.json"
